services:
  service1:
    build:
      context: ./Service1
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

  service2:
    build:
      context: ./Service2
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - app-network

  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - service1
      - service2
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
